#콘솔 로그 레벨 변경
logging:
  level:
    root: debug

spring:
  # DB 연결
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_BOOT
    password: SPRING_BOOT

  # application
  application:
    name: hello-spring

  # JSP 경로 추가
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


# mybatis 연동 설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/**/mapper/*Mapper.xml